name: merger

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install python-chess

      - name: 🏗️ Merge BIN files
        run: |
          cat pgn/Endogenetic-Bot.pgn pgn/Exogenetic-Bot.pgn pgn/MaggiChess16.pgn pgn/NNUE_Drift.pgn pgn/NimsiluBot.pgn pgn/ToromBot.pgn > combined.pgn

      - name: Trigger bot workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'polygot.yml',
              ref: 'main'
            })

      - name: 💾 Commit merged BIN file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.pgn
          git commit -m "♟️ Auto-merge Polyglot books [skip ci]" || echo "No changes to commit"
          git push
