name: Create

on:
  workflow_dispatch:
    inputs:
      bin_name:
        description: "Enter the BIN book name"
        required: true
        default: "SF"

jobs:
  convert:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Book 
      shell: cmd
      run: create.bat

    - name: Upload PGN and BIN files
      uses: actions/upload-artifact@v4
      with:
        name: Book
        path: |
          ${{ github.event.inputs.bin_name }}.bin
