name: Download

on:
  workflow_dispatch:
    inputs:
      bot_name:
        description: "Enter the Lichess bot username"
        required: true
        default: "indianguyplayz"

jobs:
  download-wins:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Calculate “since” timestamp (1 Mar 2025 00:00 UTC)
        id: time
        run: |
          SINCE=$(date -d "2025-03-01 00:00:00 UTC" +%s)000
          echo "since=$SINCE" >> "$GITHUB_OUTPUT"

      - name: Download
        run: |
          curl -L "https://lichess.org/api/games/user/${{ github.event.inputs.bot_name }}" \
            -G \
            --data-urlencode "since=${{ steps.time.outputs.since }}" \
            -d "result=draw" \
            -H "Accept: application/x-chess-pgn" \
            -o "${{ github.event.inputs.bot_name }}.pgn"

      - name: Upload PGN 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.bot_name }}
          path: "Nothing.pgn"

