name: Download

on:
  workflow_dispatch:
    inputs:
      bot_name:
        description: "Enter the Lichess bot username"
        required: true
        default: "indianguyplayz"

jobs:
  download-wins:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Calculate “since” timestamp (1 Mar 2025 00:00 UTC)
        id: time
        run: |
          SINCE=$(date -d "2025-03-01 00:00:00 UTC" +%s)000
          echo "since=$SINCE" >> "$GITHUB_OUTPUT"

      - name: Download PGN
        run: |
          FILE="${{ github.event.inputs.bot_name }}.pgn"
          curl -L "https://lichess.org/api/games/user/${{ github.event.inputs.bot_name }}" \
            -G \
            --data-urlencode "since=${{ steps.time.outputs.since }}" \
            -H "Accept: application/x-chess-pgn" \
            -o "$FILE"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push PGN file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE="${{ github.event.inputs.bot_name }}.pgn"

          # If file doesn't exist yet, add it
          if [ ! -f "$FILE" ]; then
            echo "Created new PGN file for ${{ github.event.inputs.bot_name }}" > "$FILE"
          fi

          git add "$FILE"
          git commit -m "Update PGN file for ${{ github.event.inputs.bot_name }}" || echo "No changes to commit"
          git push
