name: Download Exogenetic-Bot

on:
  workflow_dispatch:      # run by hand whenever you need

jobs:
  download-wins:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Calculate “since” timestamp (1 Mar 2025 00:00 UTC)
        id: time
        run: |
          SINCE=$(date -d "2025-03-01T00:00:00Z" +%s)000
          echo "since=$SINCE" >> "$GITHUB_OUTPUT"

      - name: Download
        run: |
          curl -L "https://lichess.org/api/games/user/Exogenetic-Bot" \
            -G \
            --data-urlencode "since=${{ steps.time.outputs.since }}" \
            -d "perfType=bullet,blitz,rapid,classical" \
            -d "result=draw" \
            -H "Accept: application/x-chess-pgn" \
            -o Exogenetic-Bot.pgn

      - name: Upload PGN file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Exogenetic-Bot_games_pgn
          path: Exogenetic-Bot.pgn
